models/person.py
from db import db
from models.servicenote import ServiceNote


language_association = db.Table(
    'language_association',
    db.Column('person_id', db.Integer, db.ForeignKey('person.id'), primary_key=True),
    db.Column('language_id', db.Integer, db.ForeignKey('language.id'), primary_key=True),
)


class Person(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String)
    last_name = db.Column(db.String)
    email = db.Column(db.String)
    phone = db.Column(db.String)
    origin_country = db.Column(db.String)

    languages = db.relationship('Language', secondary=language_association)

    def service_notes(self, service: int):
        return ServiceNote.query.filter_by(service_id=service).all()

models/user.py
import bcrypt

from db import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    name = db.Column(db.String)
    email = db.Column(db.String, unique=True)
    password = db.Column(db.String)

    person_id = db.Column(db.Integer, db.ForeignKey('person.id'))
    person = db.relationship('Person')

    service_id = db.Column(db.Integer, db.ForeignKey('service.id'))
    service = db.relationship('Service')

    def __init__(self, name: str, email: str, password: str):
        self.name = name
        self.email = email
        self.password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    def check_password(self, compare_to) -> bool:
        return bcrypt.checkpw(compare_to.encode('utf-8'), self.password.encode('utf-8'))

    def is_active(self) -> bool:
        return True

    def get_id(self) -> int:
        return self.id

    def is_authenticated(self) -> bool:
        return True

    def is_anonymous(self) -> bool:
        return False

routes/person.py
from flask import Blueprint, request, render_template, redirect, url_for, flash
from dateutil.parser import parse
from datetime import datetime

from db import db
import data
import models

person_app = Blueprint('person', __name__, url_prefix='/person')


@person_app.route('/find', methods=['GET', 'POST'])
def find():
    if request.method == 'GET':
        return render_template('lookup_user.html')

    person_id = request.form.get('person-id')
    last_name = request.form.get('last-name')

    person = models.Person.query.filter_by(id=person_id, last_name=last_name).first()
    if not person:
        flash('Unable to find person')
        return render_template('lookup_user.html')

    return redirect(url_for('.view', person_id=person.id))


@person_app.route('/add', methods=['GET', 'POST'])
def add():
    if request.method == 'GET':
        return render_template(
            'person_add.html',
            countries=data.get_countries(),
            languages=models.Language.query.all(),
        )

    first_name = request.form.get('first-name')
    last_name = request.form.get('last-name')
    email = request.form.get('email')
    phone = request.form.get('phone')
    country = request.form.get('country')
    language = request.form.get('language')

    person = models.Person()
    person.first_name = first_name
    person.last_name = last_name
    person.email = email
    person.phone = phone
    person.origin_country = country

    language = models.Language.query.get(language)
    print(language)
    person.languages.append(language)

    db.session.add(person)
    db.session.commit()

    return redirect(url_for('.view', person_id=person.id))


@person_app.route('/<int:person_id>')
def view(person_id):
    person = models.Person.query.get(person_id)
    if not person:
        flash('Unable to find person')
        return redirect(url_for('.find'))

    return render_template('person_view.html', person=person)


@person_app.route('/note', methods=['POST'])
def note():
    person = request.form.get('person')
    service = request.form.get('service')
    note = request.form.get('note')

    service_note = models.ServiceNote()
    service_note.note = note
    service_note.person_id = person
    service_note.service_id = service
    service_note.date = datetime.now()

    db.session.add(service_note)
    db.session.commit()

    return redirect(url_for('.view', person_id=person))


@person_app.route('/history', methods=['POST'])
def history():
    person = request.form.get('person')
    service = request.form.get('service')

    started_at = request.form.get('started-at')
    ended_at = request.form.get('ended-at')
    case_notes = request.form.get('case-notes')

    history = models.ServiceHistory()
    history.person_id = person
    history.service_id = service
    try:
        history.started_at = parse(started_at)
    except ValueError:
        print('no started at')
        history.started_at = None
    try:
        history.ended_at = parse(ended_at)
    except ValueError:
        print('no ended at')
        history.ended_at = None
    history.case_notes = case_notes

    db.session.add(history)
    db.session.commit()

    return redirect(url_for('.view', person_id=person))


@person_app.route('/appointment', methods=['POST'])
def appointment():
    person = request.form.get('person')
    service = request.form.get('service')
    at = request.form.get('date')
    message = request.form.get('message')

    appointment = models.ServiceReminder()
    appointment.person_id = person
    appointment.service_id = service
    try:
        appointment.date = parse(at)
    except ValueError:
        appointment.date = None
    appointment.message = message

    db.session.add(appointment)
    db.session.commit()

    return redirect(url_for('.view', person_id=person))

routes/user.py
from flask import Blueprint, abort, jsonify, redirect, request, url_for, render_template
from flask_login import login_user, logout_user

import models
from db import db

user_app = Blueprint('login', __name__, url_prefix='/auth')


@user_app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')

    email = request.form.get('email')
    password = request.form.get('password')

    user = models.User.query.filter_by(email=email).first()
    if not user:
        return abort(401)

    if not user.check_password(password):
        return abort(401)

    login_user(user)

    print(user)
    print(user.person, user.service)

    if user.person:
        return redirect(url_for('profile.view'))

    if user.service:
        return redirect(url_for('person.find'))

    return redirect(url_for('home'))


@user_app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('home'))


@user_app.route('/register', methods=['POST'])
def register():
    user = models.User(
        name=request.form.get('name'),
        email=request.form.get('email'),
        password=request.form.get('password'),
    )
    db.session.add(user)
    db.session.commit()

    return 'Added user.'


@user_app.route('/_users')
def hidden_users():
    users = models.User.query.all()

    return jsonify(list(map(lambda user: {'id': user.id, 'email': user.email}, users)))

templates/Landing.html
{% extends '_main.html' %}

{% set page = 'home' %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1>Robin</h1>

    <p>
      Make the lives of people easier by enabling a seamless flow between essential services.
    </p>
  </div>
</div>
{% endblock %}

templates/_main.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Robin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/theme.css') }}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <style>
    body {
      text-rendering: optimizeLegibility;
    }
  </style>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ url_for('home') }}">Robin</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item {% if page == 'home' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('home') }}">Home</span></a>
        </li>
        <li class="nav-item {% if page == 'about' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('about') }}">About</span></a>
        </li>
        {% if current_user.is_authenticated %}
        {% if current_user.service %}
        <li class="nav-item {% if page == 'lookup' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('person.find') }}">Find person</a>
        </li>
        {% elif current_user.person %}
        <li class="nav-item {% if page == 'person' %}active{% endif %}">
          <a class="nav-link" href="{{ url_for('profile.view') }}">View history</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('login.logout') }}">Sign out</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('login.login') }}">Sign in</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% block content %}{% endblock %}

  <footer class="text-muted text-center mt-4">
    <div class="container">
      <p>
        Made with <span style="color: #a77bdb">&hearts;</span> at <a href="https://globalhack.org/globalhack7/">GlobalHack
          VII</a> by Greg Cordover &amp; Matt Sauer
      </p>
    </div>
  </footer>

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

</body>

</html>

templates/about.html
{% extends '_main.html' %}

{% set page = 'about' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Robin</h1>
            <h2>Centralized source for Immigrant services to increase synergies between service providers.</h2>

            <p>
                By opting into this program service providers you go to will be able to see relevant data about your
                past experiences to help you receive a higher quality of service in the future.
            </p>
            <p>
                There are over 125,000 foreign-born residents in the St. Louis Metro area, each with unique needs and
                paths through the system. When you get them to register with Robin, you can help us build an idea of
                the support networks most FB residents utilize, and in return it provides them a way to provide you
                feedback on what they thought of the services rendered.
            </p>
            <p>
                The most beneficial use of this is the shared case-notes and outstanding appointments view. This is a
                place you can add to after any meetings or interactions with those individuals where you can give
                everyone who is working with them an update on what occurred.
            </p>
            <p>
                A use case of this would be:<br>
                You are with a client who has lost their Social Security card, and they have to obtain a new one. They
                go to a urgent care clinic for a procedure, and the social worker there checks this system, and finds
                the existing notes, and updates it with more information. This would help decrease the double work
                required by them also attempting to assist them with filling for a replacement social security card.
            </p>
        </div>
    </div>
</div>
{% endblock %}

templates/landing.html
{% extends '_main.html' %}

{% set page = 'home' %}

{% block content %}
<div class="jumbotron">
  <div class="container">
    <h1>Robin</h1>
    <h2>Your centralized service portal for foreign-born individuals</h2>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
      <p>
        Opting into Robin allows you to share relevant data with service providers instead of having to start new every
        time. By allowing service providers to access your data and see what has or hasn't worked well for you in the
        past, you can recieve a better and easier experience.
      </p>
    </div>
  </div>
</div>
{% endblock %}

templates/login.html
{% extends '_main.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-4 offset-md-4">
            <h1>Sign in</h1>

            {% for alert in get_flashed_messages() %}
            <div class="alert alert-danger">
                {{ alert }}
            </div>
            {% endfor %}

            <form method="POST">
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" name="email" class="form-control" id="email">
                </div>

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>

                <button type="submit" class="btn btn-primary btn-lg">Sign in</button>
            </form>

            <div>
                <h4>Testing Logins</h4>
                <a href="javascript:log('provider@robin', 'provider');" class="btn btn-sm btn-secondary">provider</a>
                <a href="javascript:log('provider2@robin', 'provider');" class="btn btn-sm btn-secondary">provider2</a>
                <a href="javascript:log('user@robin', 'user');" class="btn btn-sm btn-secondary">user</a>
            </div>
        </div>
    </div>

    <script>
        function log(email, password) {
            document.getElementById('email').value = email;
            document.getElementById('password').value = password;
        }
    </script>
</div>
{% endblock %}

templates/lookup_user.html
{% extends '_main.html' %}

{% set page = 'lookup' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-4 offset-md-4">
            <h1>Find Person</h1>

            {% for alert in get_flashed_messages() %}
            <div class="alert alert-danger">
                {{ alert }}
            </div>
            {% endfor %}

            <form method="POST" action="{{ url_for('person.find') }}">
                <div class="form-group">
                    <label for="person-id">Person ID</label>
                    <input type="text" class="form-control" id="person-id" name="person-id" placeholder="Person ID">
                </div>

                <div class="form-group">
                    <label for="last-name">Last Name</label>
                    <input type="text" class="form-control" id="last-name" name="last-name" placeholder="Last Name">
                </div>

                <button type="submit" class="btn btn-primary btn-lg">Find</button>
            </form>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-sm-12 col-md-4 offset-md-4">
            <p>
                New Person?
            </p>

            <a href="{{ url_for('person.add') }}" class="btn btn-secondary">Add</a>
        </div>
    </div>
</div>

<div id="input-helper" style="display: none; background-color: lightgray; position: fixed; padding: 10px; right: 0; bottom: 0; height: 100px; width: 300px;">
    <h2>Input Helper</h2>

    <div>
        No suggestions
    </div>
</div>

<script src="{{ url_for('static', filename='js/letters.js') }}"></script>
<script>
    new LetterSuggestor('input[name$="-name"]');
</script>
{% endblock %}

templates/person_add.html
{% extends '_main.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-4 offset-md-4">
            <h1>Add Person</h1>

            {% for alert in get_flashed_messages() %}
            <div class="alert alert-danger">
                {{ alert }}
            </div>
            {% endfor %}

            <form method="POST" action="{{ url_for('person.add') }}">
                <div class="form-group">
                    <label for="first-name">First Name</label>
                    <input type="text" class="form-control" id="first-name" name="first-name" placeholder="First Name">
                </div>

                <div class="form-group">
                    <label for="last-name">Last Name</label>
                    <input type="text" class="form-control" id="last-name" name="last-name" placeholder="Last Name">
                </div>

                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Email Address">
                </div>

                <div class="form-group">
                    <label for="phone">Phone Number</label>
                    <input type="tel" class="form-control" id="phone" name="phone" placeholder="Phone Number">
                </div>

                <div class="form-group">
                    <label for="country">Country of Origin</label>
                    <select id="country" name="country" class="form-control">
                        {% for country in countries %}
                        <option value="{{ country.name }}">{{ country.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="language">Primary Language</label>
                    <select id="language" name="language" class="form-control">
                        {% for language in languages %}
                        <option value="{{ language.id }}">{{ language.name }}</option>
                        {% endfor %}
                    </select>
                </div>

                <button type="submit" class="btn btn-primary btn-lg">Add</button>
            </form>
        </div>
    </div>
</div>

<div id="input-helper" style="display: none; background-color: lightgray; position: fixed; padding: 10px; right: 0; bottom: 0; height: 100px; width: 300px;">
    <h2>Input Helper</h2>

    <div>
        No suggestions
    </div>
</div>

<script src="{{ url_for('static', filename='js/letters.js') }}"></script>
<script>
    new LetterSuggestor('input[name$="-name"]');
</script>
{% endblock %}

templates/person_view.html
{% extends '_main.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>{{ person.first_name }} {{ person.last_name }} (ID {{ person.id }})</h1>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <h2>Information</h2>

            <dl class="row">
                <dt class="col-md-4">Email</dt>
                <dd class="col-md-8">{{ person.email }}</dd>

                <dt class="col-md-4">Phone</dt>
                <dd class="col-md-8">{{ person.phone }}</dd>

                <dt class="col-md-4">Country</dt>
                <dd class="col-md-8">{{ person.origin_country }}</dd>

                <dt class="col-md-4">Prefered Language</dt>
                <dd class="col-md-8">
                    {% if person.languages | length > 0 %}
                    {{ person.languages[0].name }}
                    {% else %}
                    Unknown
                    {% endif %}
                </dd>
            </dl>
        </div>

        <div class="col-sm-12 col-md-6">
            <h2>Internal notes</h2>

            {% for note in person.service_notes(current_user.service.id) %}
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">{{ note.date }}</h5>
                    <p class="card-text">
                        {{ note.note }}
                    </p>
                </div>
            </div>
            {% endfor %}

            <h2>Add internal note</h2>

            <form method="POST" action="{{ url_for('person.note') }}">
                <input type="hidden" name="person" value="{{ person.id }}">
                <input type="hidden" name="service" value="{{ current_user.service.id }}">

                <div class="form-group">
                    <label for="internal-note">Note</label>
                    <textarea class="form-control" name="note" id="internal-note" placeholder="Note"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Add note</button>
            </form>
        </div>

        <div class="col-sm-12 col-md-6">
            <h2>History</h2>

            {% for event in person.history %}
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">
                        {{ event.service.name }} @
                        {% if event.started_at %}
                            {{ event.started_at }} -
                        {% endif %}
                        {{ event.ended_at }}
                    </h5>
                    <p class="card-text">
                        {{ event.case_notes }}
                    </p>
                </div>
            </div>
            {% else %}
            <p>None found.</p>
            {% endfor %}

            <h2>Add to history</h2>

            <form method="POST" action="{{ url_for('person.history') }}">
                <input type="hidden" name="person" value="{{ person.id }}">
                <input type="hidden" name="service" value="{{ current_user.service.id }}">

                <div class="form-group">
                    <label for="started-at">Started at</label>
                    <input type="date" class="form-control" id="started-at" name="started-at" placeholder="Started at">
                </div>

                <div class="form-group">
                    <label for="ended-at">Ended at</label>
                    <input type="date" class="form-control" id="ended-at" name="ended-at" placeholder="Ended at">
                </div>

                <div class="form-group">
                    <label for="case-notes">Case notes</label>
                    <textarea class="form-control" id="case-notes" name="case-notes" placeholder="Case notes"></textarea>
                    <small class="form-text text-muted">Case notes are visible between services but not to the person.</small>
                </div>

                <button type="submit" class="btn btn-primary">Add event</button>
            </form>
        </div>

        <div class="col-sm-12 col-md-6">
            <h2>Appointments</h2>

            {% for appointment in person.appointments %}
            <div class="card mb-2">
                <div class="card-body">
                    <h5 class="card-title">{{ appointment.service.name }} @ {{ appointment.date }}</h5>
                    <p class="card-text">
                        {{ appointment.message }}
                    </p>
                </div>
            </div>
            {% else %}
            <p>None scheduled.</p>
            {% endfor %}

            <h2>Add appointment</h2>

            <form method="POST" action="{{ url_for('person.appointment') }}">
                <input type="hidden" name="person" value="{{ person.id }}">
                <input type="hidden" name="service" value="{{ current_user.service.id }}">

                <div class="form-group">
                    <label for="date">Date</label>
                    <input class="form-control" type="datetime-local" name="date" id="date" placeholder="Date">
                </div>

                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea class="form-control" name="message" id="message" placeholder="Message"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Add appointment</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/service_history_add.html
{% extends '_main.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Add service history item</h1>
        </div>
    </div>
</div>
{% endblock %}

templates/type_preview.html
<div class="col-md-3 col-sm-4">
  <div class="panel panel-primary">
    <div class="panel-heading">Service Type</div>
    <div class="panel-body"><img src="https://placehold.it/150x80?text=Service Type" class="img-responsive" style="width:100%" alt="Image"></div>
    <div class="panel-footer">Service Description</div>
  </div>
</div>

templates/user_view.html
{% extends '_main.html' %}

{% set page = 'person' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Hello {{ current_user.person.first_name }} {{ current_user.person.last_name }}</h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <h2>My history</h2>

            {% for event in current_user.person.history %}
                <div class="card col-md-4">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.service.name }}</h5>
                        <h6 class="card-subtitle mb-2">
                            {% if event.started_at %}
                                Started {{ event.started_at }} - Ended
                            {% endif %}
                            {{ event.ended_at }}
                        </h6>
                        <p class="card-text">
                            No feedback provided.
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}